feitwnd:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: FeiTwnd
    username: root
    password: Sql_050922
  redis:
    host: localhost
    port: 6379
    password: Redis_050922
    database: 0