server:
  port: 5922

spring:
  application:
    name: FeiTwndBackend

    #数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/FeiTwnd?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sql_050922

mybatis:
  configuration:
    #开启驼峰命名映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
